name: Release

on:
  push:
    branches:
      - main

env:
  python_version: 3.11

jobs:
  release-test:
    uses: ./.github/workflows/test.yml
  release:
    runs-on: ubuntu-latest
    concurrency: release
    needs: [ release-test ]
    permissions:
      id-token: write
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: bot_token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.bot_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      - name: Install poetry & python-semantic-release
        run: pipx install poetry~=1.8.3 python-semantic-release~=9.8.6

      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
          cache: "poetry"

      - name: Python Semantic Release
        id: release
        env:
          GH_TOKEN: ${{ steps.bot_token.outputs.token }}
          GIT_COMMIT_AUTHOR: ${{ vars.BOT_GIT_COMMIT_AUTHOR }}
        run: semantic-release version --commit

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.release.outputs.released == 'true'
