name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry~=1.8.3

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with=dev --with=benchmark --all-extras --no-interaction
      - name: Black
        run: poetry run black --check .
      - name: Isort
        run: poetry run isort --check-only .
      - name: Mypy
        run: poetry run mypy .
      - name: Pylint
        run: poetry run pylint
      - name: Pytest
        run: poetry run pytest --cov
